"use client";
import { useEffect, useState } from 'react';
import { Plus, WalletCards, RefreshCw, Pencil, Archive, Check, X } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

type Plan = { id:string; name:string; price:number; currency:'INR'; interval:'monthly'|'yearly'; trialDays:number; active:boolean; features:string[] };
const empty = { id:'', name:'', price:'', interval:'monthly', trialDays:'0', features:'' };

export default function Plans() {
  const { idToken } = useAuth();
  const [plans,setPlans] = useState<Plan[]>([]); const [open,setOpen] = useState(false); const [editing,setEditing] = useState<Plan|null>(null); const [form,setForm] = useState<any>(empty); const [status,setStatus] = useState('');
  const load = async()=>{ if(!idToken)return; const r=await fetch('/api/admin/plans',{headers:{Authorization:`Bearer ${idToken}`},cache:'no-store'}); const j=await r.json(); if(r.ok)setPlans(j.data.items||[]); else setStatus(j.error||'Unable to load plans'); };
  useEffect(()=>{load()},[idToken]);
  const startNew=()=>{setEditing(null);setForm(empty);setStatus('');setOpen(true)};
  const startEdit=(p:Plan)=>{setEditing(p);setForm({id:p.id,name:p.name,price:String(p.price),interval:p.interval,trialDays:String(p.trialDays||0),features:(p.features||[]).join('\n')});setStatus('');setOpen(true)};
  const save=async(e:any)=>{e.preventDefault(); if(!idToken)return; setStatus('Saving…'); const payload={id:String(form.id).trim().toLowerCase(),name:String(form.name).trim(),price:Number(form.price),currency:'INR',interval:form.interval,trialDays:Number(form.trialDays||0),active:true,features:String(form.features||'').split('\n').map((x:string)=>x.trim()).filter(Boolean)}; const r=await fetch('/api/admin/plans',{method:editing?'PATCH':'POST',headers:{Authorization:`Bearer ${idToken}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}); const j=await r.json(); if(!r.ok){setStatus(j.error||'Plan save failed');return} setStatus('Saved');setOpen(false);setEditing(null);await load();};
  const archive=async(id:string)=>{if(!idToken||!confirm('Archive this plan? It will no longer be available for new purchases.'))return; const r=await fetch(`/api/admin/plans?id=${encodeURIComponent(id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${idToken}`}});const j=await r.json();if(!r.ok)setStatus(j.error||'Archive failed');else await load()};
  return <main className="space-y-6"><header className="skeuo-panel flex items-center justify-between p-6"><div><p className="eyebrow">MONETIZATION</p><h1 className="mt-2 text-3xl font-black">Subscription Plans</h1><p className="mt-1 text-sm text-dark-muted">Live server-controlled INR prices and entitlements for Razorpay orders.</p></div><div className="flex gap-2"><button onClick={load} className="skeuo-button"><RefreshCw size={16}/></button><button onClick={startNew} className="skeuo-button-primary inline-flex items-center gap-2"><Plus size={16}/> New plan</button></div></header>
    {open&&<form onSubmit={save} className="skeuo-card grid gap-4 p-6 md:grid-cols-2"><input name="id" value={form.id} onChange={e=>setForm({...form,id:e.target.value})} disabled={!!editing} required pattern="[A-Za-z0-9_-]{2,80}" placeholder="plan_monthly" className="input"/><input name="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="Plan name" className="input"/><input name="price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required type="number" min="1" step="1" placeholder="Price in INR, e.g. 99" className="input"/><select name="interval" value={form.interval} onChange={e=>setForm({...form,interval:e.target.value})} className="input"><option value="monthly">monthly</option><option value="yearly">yearly</option></select><input name="trialDays" value={form.trialDays} onChange={e=>setForm({...form,trialDays:e.target.value})} type="number" min="0" max="30" className="input" placeholder="Trial days"/><textarea name="features" value={form.features} onChange={e=>setForm({...form,features:e.target.value})} placeholder="One feature per line" className="input min-h-32 md:col-span-2"/><div className="flex gap-2 md:col-span-2"><button className="skeuo-button-primary inline-flex items-center gap-2"><Check size={15}/>{editing?'Update plan':'Save plan'}</button><button type="button" onClick={()=>setOpen(false)} className="skeuo-button inline-flex items-center gap-2"><X size={15}/> Cancel</button></div>{status&&<p className="text-sm text-dark-muted md:col-span-2">{status}</p>}</form>}
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{plans.map(p=><article key={p.id} className={`skeuo-card p-5 ${!p.active?'opacity-60':''}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><WalletCards className="text-accent"/><div><h2 className="font-black">{p.name}</h2><p className="text-xs text-dark-muted">{p.id} · {p.interval}</p></div></div><div className="flex gap-1"><button onClick={()=>startEdit(p)} className="skeuo-button p-2" title="Edit"><Pencil size={14}/></button><button onClick={()=>archive(p.id)} className="skeuo-button p-2" title="Archive"><Archive size={14}/></button></div></div><p className="mt-5 text-3xl font-black">₹{Number(p.price||0).toLocaleString('en-IN')}</p><p className="mt-1 text-xs text-dark-muted">Trial: {p.trialDays||0} days · {p.active?'Active':'Archived'}</p>{p.features?.length>0&&<ul className="mt-4 space-y-1 text-xs text-dark-muted">{p.features.slice(0,5).map((f,i)=><li key={i}>• {f}</li>)}</ul>}</article>)}{!plans.length&&<div className="skeuo-card p-10 text-center text-sm text-dark-muted md:col-span-2 lg:col-span-3">No subscription plans configured.</div>}</div></main>
}
