import { Track, Podcast, Episode } from "@/types";

export const catalogTracks: Track[] = [
  { id:"track_1", title:"Neon Horizon", slug:"neon-horizon", description:"Synthwave electronic journey across futuristic cyberpunk landscapes.", thumbnailUrl:"https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80", audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", categoryId:"electronic", creatorId:"demo", accessType:"FREE", status:"PUBLISHED", featured:true, explicitContent:false, language:"en", releaseDate:Date.now(), duration:372, playCount:1420, likeCount:320, createdAt:Date.now(), updatedAt:Date.now() },
  { id:"track_2", title:"Deep Focus Ambient", slug:"deep-focus-ambient", description:"Relaxing atmospheric soundscapes designed for deep concentration and flow.", thumbnailUrl:"https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80", audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3", categoryId:"ambient", creatorId:"demo", accessType:"PREMIUM", status:"PUBLISHED", featured:true, explicitContent:false, language:"en", releaseDate:Date.now(), duration:420, playCount:890, likeCount:245, createdAt:Date.now(), updatedAt:Date.now() },
  { id:"track_3", title:"Midnight Jazz Lounge", slug:"midnight-jazz-lounge", description:"Smooth saxophones and warm upright bass from an underground club.", thumbnailUrl:"https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80", audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", categoryId:"jazz", creatorId:"demo", accessType:"FREE", status:"PUBLISHED", featured:true, explicitContent:false, language:"en", releaseDate:Date.now(), duration:310, playCount:2300, likeCount:512, createdAt:Date.now(), updatedAt:Date.now() },
  { id:"track_4", title:"Future of AI — Episode 42", slug:"future-of-ai-42", description:"A long-form conversation about AI, safety and creative technology.", thumbnailUrl:"https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop&q=80", audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3", categoryId:"podcast", creatorId:"demo", accessType:"PREMIUM", status:"PUBLISHED", featured:true, explicitContent:false, language:"en", releaseDate:Date.now(), duration:1840, playCount:4100, likeCount:980, createdAt:Date.now(), updatedAt:Date.now() },
];

export const catalogPodcasts: Podcast[] = [
  { id:"pod_1", title:"Future of AI", slug:"future-of-ai", description:"Technology, creativity and the people building tomorrow.", coverUrl:"https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&auto=format&fit=crop&q=80", creatorId:"demo", categoryId:"technology", language:"en", status:"PUBLISHED", featured:true, subscriberCount:12400, createdAt:Date.now(), updatedAt:Date.now() },
  { id:"pod_2", title:"The Creator Room", slug:"the-creator-room", description:"Honest conversations with musicians, filmmakers and makers.", coverUrl:"https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop&q=80", creatorId:"demo", categoryId:"creators", language:"en", status:"PUBLISHED", featured:true, subscriberCount:8200, createdAt:Date.now(), updatedAt:Date.now() },
];

export const catalogEpisodes: Episode[] = catalogTracks.filter(t => t.categoryId === "podcast").map((t, i) => ({ id:t.id, podcastId:"pod_1", title:t.title, slug:t.slug, description:t.description, episodeNumber:i+1, seasonNumber:1, thumbnailUrl:t.thumbnailUrl, audioUrl:t.audioUrl, duration:t.duration, accessType:t.accessType, publishedAt:t.releaseDate, status:t.status }));

export function formatDuration(seconds:number){ const m=Math.floor(seconds/60); const s=seconds%60; return `${m}:${String(s).padStart(2,"0")}`; }
