import { NextRequest } from 'next/server';
import { z } from 'zod';
import { adminAuth,adminDb } from '@/lib/firebase-admin';
import { requireRole } from '@/lib/server-auth';
import { fail,ok } from '@/lib/api-response';

const patchSchema=z.object({userId:z.string().min(1).max(200),action:z.enum(['edit','block','unblock']),displayName:z.string().trim().min(1).max(120).optional(),role:z.enum(['USER','PREMIUM_USER','EDITOR','MODERATOR','ADMIN','SUPER_ADMIN']).optional(),email:z.string().email().max(320).optional()});
export async function GET(request:NextRequest){try{await requireRole(request,['ADMIN','SUPER_ADMIN','MODERATOR']);if(!adminDb)return fail('Server is not configured',503);const limit=Math.min(Math.max(Number(request.nextUrl.searchParams.get('limit')||100),1),100);const snap=await adminDb.collection('users').orderBy('createdAt','desc').limit(limit).get();return ok({items:snap.docs.map(d=>({id:d.id,...d.data()}))})}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);return fail('Unable to load users',500)}}
export async function PATCH(request:NextRequest){try{const{user,role:actorRole}=await requireRole(request,['ADMIN','SUPER_ADMIN']);if(!adminDb||!adminAuth)return fail('Server is not configured',503);const input=patchSchema.parse(await request.json());if(input.userId===user.uid&&input.action!=='edit')return fail('You cannot block your own account',400);const targetRef=adminDb.collection('users').doc(input.userId);const target=await targetRef.get();if(!target.exists)return fail('User not found',404);const targetRole=String(target.data()?.role||'USER');if(input.role==='SUPER_ADMIN'&&actorRole!=='SUPER_ADMIN')return fail('Only a super admin can grant this role',403);if(input.role&&actorRole!=='SUPER_ADMIN'&&(targetRole==='SUPER_ADMIN'||input.role==='ADMIN'))return fail('Only a super admin can change privileged roles',403);const now=Date.now();const update:Record<string,unknown>={updatedAt:now};if(input.action==='block')update.banned=true;if(input.action==='unblock')update.banned=false;if(input.action==='edit'&&input.displayName!==undefined)update.displayName=input.displayName;if(input.action==='edit'&&input.role!==undefined)update.role=input.role;if(input.action==='edit'&&input.email!==undefined){await adminAuth.updateUser(input.userId,{email:input.email});update.email=input.email}if(input.action==='edit'&&input.displayName!==undefined)await adminAuth.updateUser(input.userId,{displayName:input.displayName});if(input.action!=='edit'){await adminAuth.updateUser(input.userId,{disabled:input.action==='block'});if(input.action==='block')await adminAuth.revokeRefreshTokens(input.userId)}await targetRef.set(update,{merge:true});await adminDb.collection('auditLogs').add({actorId:user.uid,action:input.action==='edit'?'USER_EDIT':input.action==='block'?'USER_BLOCK':'USER_UNBLOCK',targetId:input.userId,createdAt:now});return ok({id:input.userId})}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);if(e?.name==='ZodError')return fail('Invalid user payload',400);console.error('[admin/users] mutation failed',e);return fail('Unable to update user',500)}}
