"use client";
import { useEffect, useState } from "react";
import { Plus, RefreshCw, Trophy } from "lucide-react";
import { useAuth } from "@/context/AuthContext";

export default function AdminTournamentsPage() {
  const { idToken } = useAuth();
  const [items, setItems] = useState<any[]>([]);
  const [form, setForm] = useState({ title: "", game: "", description: "", rules: "", maxPlayers: 32, entryCoins: 0, prizeCoins: 0, startsAt: "" });
  const load = async () => { const r = await fetch("/api/tournaments", { cache: "no-store" }); const j = await r.json(); setItems(j.data?.tournaments || []); };
  useEffect(() => { void load(); }, []);
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!idToken) return; const body = { ...form, startsAt: form.startsAt ? new Date(form.startsAt).getTime() : Date.now() + 86400000, status: "REGISTRATION_OPEN", format: "SINGLE_ELIMINATION" }; const r = await fetch("/api/tournaments", { method: "POST", headers: { Authorization: `Bearer ${idToken}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (r.ok) { setForm({ title: "", game: "", description: "", rules: "", maxPlayers: 32, entryCoins: 0, prizeCoins: 0, startsAt: "" }); await load(); } };
  const setStatus = async (id: string, status: string) => { if (!idToken) return; await fetch(`/api/tournaments/${id}`, { method: "PATCH", headers: { Authorization: `Bearer ${idToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); await load(); };
  return <div className="space-y-7"><header className="rounded-3xl border border-accent/20 bg-accent/5 p-6"><div className="flex items-center gap-3 text-accent"><Trophy/><span className="font-black uppercase tracking-widest">Tournament control</span></div><h1 className="mt-2 text-3xl font-black">Create & manage tournaments</h1><p className="mt-2 text-sm text-dark-muted">The old podcast/payment control plane is gone from the player workflow.</p></header><form onSubmit={create} className="grid gap-4 rounded-2xl border border-dark-border bg-dark-card p-6 md:grid-cols-2"><Field label="Tournament title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Game"><input required value={form.game} onChange={e=>setForm({...form,game:e.target.value})}/></Field><Field label="Max players"><input type="number" min="2" value={form.maxPlayers} onChange={e=>setForm({...form,maxPlayers:Number(e.target.value)})}/></Field><Field label="Entry coins"><input type="number" min="0" value={form.entryCoins} onChange={e=>setForm({...form,entryCoins:Number(e.target.value)})}/></Field><Field label="Prize coins"><input type="number" min="0" value={form.prizeCoins} onChange={e=>setForm({...form,prizeCoins:Number(e.target.value)})}/></Field><Field label="Start time"><input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="Description" full><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Rules" full><textarea rows={4} value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})}/></Field><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-accent px-5 py-3 font-black text-dark md:col-span-2"><Plus size={18}/> Create tournament</button></form><section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Existing tournaments</h2><button onClick={load} className="rounded-xl border border-dark-border p-2"><RefreshCw size={17}/></button></div>{items.map(t=><div key={t.id} className="flex flex-col gap-4 rounded-2xl border border-dark-border bg-dark-card p-5 md:flex-row md:items-center md:justify-between"><div><p className="font-black">{t.title}</p><p className="text-sm text-dark-muted">{t.game} · {t.joinedPlayers}/{t.maxPlayers} players · {t.status}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setStatus(t.id,"OPEN")} className="rounded-lg border border-dark-border px-3 py-2 text-xs font-bold">Open</button><button onClick={()=>setStatus(t.id,"LIVE")} className="rounded-lg border border-dark-border px-3 py-2 text-xs font-bold">Live</button><button onClick={()=>setStatus(t.id,"COMPLETED")} className="rounded-lg border border-dark-border px-3 py-2 text-xs font-bold">Complete</button></div></div>)}</section></div>;
}
function Field({label,children,full=false}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={full?"md:col-span-2":""}><span className="mb-1 block text-xs font-bold uppercase tracking-wider text-dark-muted">{label}</span>{children}</label>}
