import { NextRequest } from 'next/server';
import { z } from 'zod';
import { adminDb } from '@/lib/firebase-admin';
import { requireRole } from '@/lib/server-auth';
import { fail, ok } from '@/lib/api-response';

const schema=z.object({id:z.string().min(1).max(200).optional(),title:z.string().trim().min(1).max(200),body:z.string().trim().min(1).max(5000),active:z.boolean().default(true)});

export async function GET(request:NextRequest){try{await requireRole(request,['ADMIN','SUPER_ADMIN','EDITOR']);if(!adminDb)return fail('Server is not configured',503);const snap=await adminDb.collection('notifications').orderBy('createdAt','desc').limit(100).get();return ok({items:snap.docs.map(doc=>({id:doc.id,...doc.data()}))});}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);console.error('[admin/notifications] list failed',e);return fail('Unable to load notifications',500)}}

export async function POST(request:NextRequest){try{const {user}=await requireRole(request,['ADMIN','SUPER_ADMIN']);if(!adminDb)return fail('Server is not configured',503);const input=schema.omit({id:true}).parse(await request.json());const ref=adminDb.collection('notifications').doc();const now=Date.now();await ref.set({id:ref.id,...input,createdAt:now,updatedAt:now,createdBy:user.uid});await adminDb.collection('auditLogs').add({actorId:user.uid,action:'NOTIFICATION_CREATE',targetId:ref.id,createdAt:now});return ok({id:ref.id},201);}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);if(e?.name==='ZodError')return fail('Invalid notification',400);console.error('[admin/notifications] create failed',e);return fail('Unable to create notification',500)}}

export async function PATCH(request:NextRequest){try{const {user}=await requireRole(request,['ADMIN','SUPER_ADMIN']);if(!adminDb)return fail('Server is not configured',503);const input=schema.parse(await request.json());if(!input.id)return fail('Notification id is required',400);const now=Date.now();await adminDb.collection('notifications').doc(input.id).set({...input,updatedAt:now,updatedBy:user.uid},{merge:true});await adminDb.collection('auditLogs').add({actorId:user.uid,action:'NOTIFICATION_UPDATE',targetId:input.id,createdAt:now});return ok({id:input.id});}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);if(e?.name==='ZodError')return fail('Invalid notification',400);console.error('[admin/notifications] update failed',e);return fail('Unable to update notification',500)}}

export async function DELETE(request:NextRequest){try{const {user}=await requireRole(request,['ADMIN','SUPER_ADMIN']);if(!adminDb)return fail('Server is not configured',503);const id=request.nextUrl.searchParams.get('id')||'';if(!id)return fail('Notification id is required',400);await adminDb.collection('notifications').doc(id).delete();await adminDb.collection('auditLogs').add({actorId:user.uid,action:'NOTIFICATION_DELETE',targetId:id,createdAt:Date.now()});return ok({id,deleted:true});}catch(e:any){if(e?.message==='UNAUTHORIZED')return fail('Authentication required',401);if(e?.message==='FORBIDDEN')return fail('Forbidden',403);console.error('[admin/notifications] delete failed',e);return fail('Unable to delete notification',500)}}
