"use client";

import { FormEvent, useEffect, useState } from "react";
import { Loader2, PlusCircle, ShieldCheck } from "lucide-react";
import { useAuth } from "@/context/AuthContext";

type Task={id:string;title:string;description:string;type:string;rewardCoins:number;target:number;active:boolean;};

export default function AdminTasksPage(){
 const {idToken}=useAuth();const [tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/tasks?admin=1',{headers:{Authorization:`Bearer ${idToken||''}`},cache:'no-store'});const j=await r.json();if(r.ok)setTasks(j.data?.items||[]);else setMessage(j.error||'Unable to load tasks')}finally{setLoading(false)}};
 useEffect(()=>{if(idToken)void load()},[idToken]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!idToken)return;setSaving(true);setMessage("");const form=new FormData(e.currentTarget);try{const r=await fetch('/api/tasks',{method:'POST',headers:{Authorization:`Bearer ${idToken}`,'Content-Type':'application/json'},body:JSON.stringify({title:String(form.get('title')||''),description:String(form.get('description')||''),type:String(form.get('type')||'CUSTOM'),rewardCoins:Number(form.get('rewardCoins')||0),target:Number(form.get('target')||1),active:true})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to create task');setMessage('Task created.');e.currentTarget.reset();await load()}catch(err:any){setMessage(err.message||'Unable to create task')}finally{setSaving(false)}};
 return <div className="mx-auto max-w-6xl space-y-7 p-5 md:p-10"><header className="rounded-3xl border border-accent/20 bg-gradient-to-br from-dark-card to-dark p-6 shadow-skeuo md:p-8"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-accent"><ShieldCheck size={15}/> Reward Operations</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Task Command Center</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-dark-muted">Create real server-backed reward tasks. Claims are recorded once and coin credits go through the protected ledger.</p></header>
 <section className="grid gap-6 lg:grid-cols-[1fr_1.4fr]"><form onSubmit={create} className="rounded-2xl border border-white/10 bg-dark-card p-6 shadow-skeuo space-y-4"><h2 className="text-xl font-black">Create task</h2><input name="title" required minLength={3} maxLength={160} placeholder="Task title" className="w-full rounded-xl border border-white/10 bg-dark p-3 text-sm outline-none"/><textarea name="description" maxLength={2000} placeholder="Task description" className="min-h-28 w-full rounded-xl border border-white/10 bg-dark p-3 text-sm outline-none"/><div className="grid grid-cols-2 gap-3"><select name="type" className="rounded-xl border border-white/10 bg-dark p-3 text-sm"><option>LISTEN</option><option>FOLLOW</option><option>SHARE</option><option>CUSTOM</option></select><input name="rewardCoins" type="number" min="1" max="100000" required placeholder="Reward coins" className="rounded-xl border border-white/10 bg-dark p-3 text-sm"/></div><input name="target" type="number" min="1" max="1000000" defaultValue="1" required placeholder="Target" className="w-full rounded-xl border border-white/10 bg-dark p-3 text-sm"/>{message&&<div className="text-sm text-dark-muted">{message}</div>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-3 text-sm font-black text-dark disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={16}/>:<PlusCircle size={16}/>} Create live task</button></form>
 <div className="rounded-2xl border border-white/10 bg-dark-card p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Active tasks</h2><span className="text-xs text-dark-muted">{tasks.length} total</span></div>{loading?<div className="py-10 text-center text-dark-muted">Loading…</div>:<div className="mt-5 space-y-3">{tasks.map(t=><div key={t.id} className="rounded-xl border border-white/10 bg-dark p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-accent">{t.type}</p><h3 className="mt-1 font-black">{t.title}</h3><p className="mt-1 text-xs text-dark-muted">Target {t.target}</p></div><span className="rounded-lg bg-accent/10 px-3 py-1.5 text-sm font-black text-accent">+{t.rewardCoins}</span></div></div>)}{!tasks.length&&<p className="py-10 text-center text-sm text-dark-muted">No active tasks.</p>}</div>}</div></section></div>
}
