"use client";
import { useState } from "react";
import { Mail, Lock, Sparkles, Chrome, ShieldCheck } from "lucide-react";
import { useToast } from "@/components/ui/Toast";
import { auth, db, googleProvider } from "@/lib/firebase";
import { signInWithEmailAndPassword, createUserWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { doc, getDoc, setDoc, serverTimestamp } from "firebase/firestore";
import { useRouter } from "next/navigation";

export default function LoginPage(){
 const [isLogin,setIsLogin]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[loading,setLoading]=useState(false); const {showToast}=useToast(); const router=useRouter();
 const saveProfile=async(u:any)=>{const ref=doc(db,"users",u.uid);const existing=await getDoc(ref);const existingRole=String(existing.data()?.role||"").toUpperCase();await setDoc(ref,{uid:u.uid,email:u.email||"",displayName:u.displayName||"",photoURL:u.photoURL||"",...(existing.exists()&&existingRole?{role:existingRole}:{role:"USER"}),isSubscribed:existing.data()?.isSubscribed===true,createdAt:existing.data()?.createdAt||serverTimestamp(),updatedAt:serverTimestamp()},{merge:true})};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{const c=isLogin?await signInWithEmailAndPassword(auth,email,password):await createUserWithEmailAndPassword(auth,email,password);if(!isLogin) await saveProfile(c.user);showToast(isLogin?"Welcome back":"Account created");router.push("/account")}catch(err:any){showToast(err?.code?.includes("invalid-credential")?"Email or password is incorrect":err?.message||"Authentication failed")}finally{setLoading(false)}};
 const google=async()=>{setLoading(true);try{const c=await signInWithPopup(auth,googleProvider);await saveProfile(c.user);router.push("/account")}catch(err:any){showToast(err?.message||"Google sign-in failed")}finally{setLoading(false)}};
 return <div className="min-h-[80vh] grid place-items-center p-4 md:p-8"><section className="w-full max-w-md rounded-3xl border border-dark-border bg-dark-card p-6 shadow-skeuo md:p-8"><div className="mb-7 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-accent text-dark shadow-skeuo-btn"><Sparkles/></div><h1 className="mt-4 text-3xl font-black">{isLogin?"Welcome back":"Join Podmen X"}</h1><p className="mt-2 text-sm text-dark-muted">{isLogin?"Your library is waiting.":"Create your free listener account."}</p></div><button onClick={google} disabled={loading} className="mb-5 flex w-full items-center justify-center gap-2 rounded-xl border border-dark-border bg-dark px-4 py-3 text-sm font-bold hover:bg-dark-surface disabled:opacity-50"><Chrome size={18}/> Continue with Google</button><div className="my-5 flex items-center gap-3 text-[11px] uppercase tracking-widest text-dark-muted"><span className="h-px flex-1 bg-dark-border"/>or<span className="h-px flex-1 bg-dark-border"/></div><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold text-dark-muted">Email</span><div className="relative"><Mail className="absolute left-3 top-3.5 text-dark-muted" size={16}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="input w-full pl-10" placeholder="you@example.com"/></div></label><label className="block"><span className="mb-2 block text-xs font-bold text-dark-muted">Password</span><div className="relative"><Lock className="absolute left-3 top-3.5 text-dark-muted" size={16}/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="input w-full pl-10" placeholder="At least 6 characters"/></div></label><button disabled={loading} className="w-full rounded-xl bg-accent py-3 font-black text-dark shadow-skeuo-btn disabled:opacity-50">{loading?"Please wait…":isLogin?"Sign in":"Create account"}</button></form><button onClick={()=>setIsLogin(v=>!v)} className="mt-5 w-full text-xs font-semibold text-dark-muted hover:text-accent">{isLogin?"New here? Create an account":"Already registered? Sign in"}</button><p className="mt-6 flex items-center justify-center gap-2 text-[11px] text-dark-muted"><ShieldCheck size={13}/> Secure authentication via Firebase</p></section></div>
}
