"use client";
import { useEffect,useState } from 'react';
import { Mic,Play,RefreshCw,Loader2 } from 'lucide-react';
import Link from 'next/link';
import { Podcast,Track } from '@/types';
import { usePlayer } from '@/components/player/PlayerProvider';

export default function PodcastsPage(){
 const[podcasts,setPodcasts]=useState<Podcast[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const{play}=usePlayer();
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/content',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load podcasts');setPodcasts(j.data?.podcasts||[])}catch(e:any){setError(e.message||'Unable to load podcasts')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const asTrack=(p:Podcast):Track|null=>p.audioUrl?{id:p.id,title:p.title,slug:p.slug,description:p.description||'Published podcast',thumbnailUrl:p.coverUrl||'',audioUrl:p.audioUrl,categoryId:p.categoryId||'podcast',creatorId:p.creatorId||'admin',accessType:p.accessType||'FREE',status:p.status,featured:Boolean(p.featured),explicitContent:false,language:p.language||'en',releaseDate:p.createdAt||Date.now(),duration:Number(p.duration||0),playCount:0,likeCount:0,createdAt:p.createdAt||Date.now(),updatedAt:p.updatedAt||Date.now()}:null;
 return <main className="mx-auto max-w-7xl space-y-8 p-4 pb-32 sm:p-6 md:p-10"><header className="skeuo-panel flex items-center justify-between p-6"><div><p className="eyebrow flex items-center gap-2"><Mic size={16}/> LIVE SHOWS</p><h1 className="mt-2 text-3xl font-black">Podcasts & Shows</h1><p className="mt-1 text-base text-dark-muted">Published shows from the live admin catalog.</p></div><button onClick={load} className="skeuo-button inline-flex items-center gap-2"><RefreshCw size={16}/> Refresh</button></header>{error&&<div className="skeuo-card p-4 text-base text-red-300">{error}</div>}{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-accent"/></div>:podcasts.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{podcasts.map(p=>{const track=asTrack(p);return <article key={p.id} className="skeuo-card p-4"><div className="flex gap-4"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-xl bg-dark-surface">{p.coverUrl?<img src={p.coverUrl} alt={p.title} className="h-full w-full object-cover"/>:<Mic className="text-accent"/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-black uppercase tracking-widest text-accent">Podcast</p><h2 className="mt-1 truncate text-lg font-black">{p.title}</h2><p className="mt-1 line-clamp-3 text-sm leading-6 text-dark-muted">{p.description||'Published podcast show.'}</p><div className="mt-3 flex flex-wrap gap-2">{track?<button onClick={()=>void play(track,[track])} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2 text-sm font-black text-dark"><Play size={15} fill="currentColor"/> Play</button>:null}<Link href={`/search?query=${encodeURIComponent(p.title)}`} className="inline-flex items-center rounded-xl border border-dark-border px-4 py-2 text-sm font-bold text-dark-muted">Find episodes</Link></div></div></div></article>})}</div>:<div className="skeuo-card p-12 text-center text-base text-dark-muted">No published podcasts are available yet.</div>}</main>
}
