"use client";
import { useState } from "react";
import { Check, Crown, Loader2, ShieldCheck, Zap, Gift } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/components/ui/Toast";

declare global { interface Window { Razorpay?: any } }
const plan={id:"plan_monthly",name:"Pro Creator & Audiophile",priceLabel:"₹99",amountPaise:9900,description:"Premium monthly access"};

export default function PricingPage(){
 const [loading,setLoading]=useState(false); const [trialLoading,setTrialLoading]=useState(false); const {idToken,user}=useAuth(); const {showToast}=useToast();
 const startTrial=async()=>{if(!user||!idToken){showToast("Please sign in to start your trial");return}setTrialLoading(true);try{const r=await fetch("/api/subscriptions/trial",{method:"POST",headers:{Authorization:`Bearer ${idToken}`}});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Trial unavailable");showToast("7-day Premium trial activated");}catch(e:any){showToast(e?.message||"Unable to start trial")}finally{setTrialLoading(false)}};
 const subscribe=async()=>{if(!user||!idToken){showToast("Please sign in before subscribing");return}setLoading(true);try{if(!window.Razorpay){await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Unable to load Razorpay checkout"));document.body.appendChild(s)})}const r=await fetch("/api/payments/create-order",{method:"POST",headers:{Authorization:`Bearer ${idToken}`,"Content-Type":"application/json"},body:JSON.stringify({planId:plan.id})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Unable to create order");await new Promise<void>((resolve,reject)=>{const rz=new window.Razorpay({key:j.data.keyId,amount:j.data.amount,currency:j.data.currency,name:"Podmen X",description:plan.description,order_id:j.data.orderId,prefill:{email:user.email||""},theme:{color:"#E5A93B"},handler:async(response:any)=>{try{const vr=await fetch("/api/payments/verify",{method:"POST",headers:{Authorization:`Bearer ${idToken}`,"Content-Type":"application/json"},body:JSON.stringify(response)});const vj=await vr.json();if(!vr.ok||!vj.ok)throw new Error(vj.error||"Verification failed");showToast("Payment verified. Premium access is being reconciled with the gateway.");resolve()}catch(e){reject(e)}}});rz.on("payment.failed",(e:any)=>reject(new Error(e?.error?.description||"Payment failed")));rz.open()});}catch(e:any){showToast(e?.message||"Checkout failed")}finally{setLoading(false)}};
 return <div className="mx-auto max-w-6xl space-y-10 p-5 pb-32 md:p-10"><header className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-black text-dark"><Crown size={14} fill="currentColor"/> PREMIUM</span><h1 className="mt-5 text-4xl font-black md:text-6xl">Your sound, unlocked.</h1><p className="mt-3 text-sm leading-6 text-dark-muted">Start with one secure 7-day free trial. When you choose a paid plan, the final amount and entitlement are controlled by the server.</p></header>
 <section className="grid gap-5 md:grid-cols-2">
  <article className="skeuo-card border-accent/30 p-7"><div className="flex items-center gap-2 text-accent"><Gift size={20}/><b>7-DAY FREE TRIAL</b></div><h2 className="mt-3 text-3xl font-black">Try Premium free</h2><p className="mt-2 text-sm text-dark-muted">One trial per account. No payment is taken to start the trial.</p><ul className="mt-6 space-y-3 text-sm">{["Premium music & podcasts","Unlimited favorites and playlists","Ad-free premium experience","Full player experience"].map(x=><li key={x} className="flex items-center gap-3"><Check size={17} className="text-accent"/>{x}</li>)}</ul><button onClick={startTrial} disabled={trialLoading} className="skeuo-button-primary mt-8 flex w-full items-center justify-center gap-2">{trialLoading?<Loader2 className="animate-spin"/>:<Gift size={18}/>} {trialLoading?"Activating…":"Start 7-day free trial"}</button></article>
  <article className="skeuo-card border-2 border-accent p-7"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-black"><Zap className="text-accent"/> {plan.name}</h2><span className="rounded-full bg-accent px-2 py-1 text-[10px] font-black text-dark">MONTHLY</span></div><p className="mt-1 text-xs text-dark-muted">Secure Razorpay checkout with server verification.</p><div className="mt-7 text-5xl font-black">{plan.priceLabel}<span className="text-sm font-normal text-dark-muted"> / month</span></div><ul className="mt-7 space-y-3 text-sm">{["Premium music & podcasts","Unlimited favorites and playlists","Ad-free premium experience","Secure payment history"].map(x=><li key={x} className="flex items-center gap-3"><Check size={17} className="text-accent"/>{x}</li>)}</ul><button onClick={subscribe} disabled={loading} className="skeuo-button-primary mt-8 flex w-full items-center justify-center gap-2">{loading?<Loader2 className="animate-spin"/>:<Crown size={18}/>} {loading?"Opening secure checkout…":"Subscribe with Razorpay"}</button><p className="mt-4 flex items-center justify-center gap-2 text-center text-[11px] text-dark-muted"><ShieldCheck size={13}/> Signature verified on the server.</p></article>
 </section></div>;
}
