"use client";
import { useState } from "react";
import { Play, Sparkles, TrendingUp, Mic2, Crown, ArrowRight } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import { catalogTracks, catalogPodcasts } from "@/lib/catalog";
import CatalogCard from "@/components/tracks/CatalogCard";
import { Track } from "@/types";

export default function HomePage(){
 const [current,setCurrent]=useState<Track|null>(null); const [favorites,setFavorites]=useState<string[]>([]);
 return <div className="mx-auto max-w-7xl space-y-12 p-4 pb-32 sm:p-6 md:p-10">
  <section className="relative overflow-hidden rounded-[2rem] border border-dark-border bg-gradient-to-br from-[#25261b] via-dark-surface to-dark p-7 shadow-skeuo md:p-12"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-accent/10 blur-3xl"/><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full bg-accent px-3 py-1 text-xs font-black text-dark"><Sparkles size={14}/> PODMEN X PREMIUM AUDIO</span><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight text-white sm:text-5xl md:text-6xl">Your world.<br/><span className="text-accent">Your sound.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-dark-muted sm:text-base">Stream music and podcasts, build your library, and unlock premium listening with one powerful audio experience.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setCurrent(catalogTracks[0])} className="inline-flex items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-black text-dark shadow-skeuo-btn"><Play size={18} fill="currentColor"/> Listen now</button><Link href="/pricing" className="inline-flex items-center gap-2 rounded-xl border border-dark-border bg-dark-card px-5 py-3 text-sm font-bold text-white">Go Premium <ArrowRight size={16}/></Link></div></div></section>
  <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-accent">For you</p><h2 className="mt-1 text-2xl font-black">Featured audio</h2></div><Link href="/explore" className="text-sm font-bold text-dark-muted hover:text-accent">See all →</Link></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{catalogTracks.map(t=><CatalogCard key={t.id} track={t} onPlay={setCurrent} isFavorite={favorites.includes(t.id)} onFavorite={()=>setFavorites(v=>v.includes(t.id)?v.filter(x=>x!==t.id):[...v,t.id])}/>)}</div></section>
  <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-accent">Shows</p><h2 className="mt-1 text-2xl font-black">Popular podcasts</h2></div><Link href="/podcasts" className="text-sm font-bold text-dark-muted hover:text-accent">Browse shows →</Link></div><div className="grid gap-4 sm:grid-cols-2">{catalogPodcasts.map(p=><article key={p.id} className="group flex gap-4 rounded-2xl border border-dark-border bg-dark-card p-4 shadow-skeuo"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-xl"><Image src={p.coverUrl} alt={p.title} fill sizes="96px" className="object-cover" unoptimized/></div><div className="min-w-0"><span className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-accent"><Mic2 size={12}/> Podcast</span><h3 className="mt-1 truncate text-lg font-bold">{p.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-dark-muted">{p.description}</p><p className="mt-2 text-[11px] text-dark-muted">{p.subscriberCount.toLocaleString()} listeners</p></div></article>)}</div></section>
  <section className="rounded-2xl border border-accent/20 bg-accent/5 p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><span className="inline-flex items-center gap-2 text-accent"><Crown size={18} fill="currentColor"/><b>Premium listening</b></span><h2 className="mt-2 text-2xl font-black">More music. More podcasts. No limits.</h2><p className="mt-2 text-sm text-dark-muted">Choose a plan and unlock premium content through secure Razorpay payments.</p></div><Link href="/pricing" className="inline-flex shrink-0 items-center justify-center rounded-xl bg-accent px-5 py-3 text-sm font-black text-dark">View plans</Link></div></section>
  {current&&<div className="fixed inset-x-3 bottom-3 z-50 rounded-2xl border border-dark-border bg-dark-surface/95 p-3 shadow-2xl backdrop-blur md:left-72"><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{current.title}</p><p className="text-xs text-dark-muted">Now playing</p></div><audio controls autoPlay src={current.audioUrl} className="h-9 w-full max-w-xl"/><button onClick={()=>setCurrent(null)} className="px-2 text-xs text-dark-muted">Close</button></div></div>}
 </div>
}
