"use client";
import { useEffect,useState } from 'react';
import { FileAudio,Plus,RefreshCw,ExternalLink,Pencil,Ban,Trash2,Check,X } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

type Item={id:string;title:string;description?:string;audioUrl:string;thumbnailUrl?:string;accessType?:'FREE'|'PREMIUM';status?:string;playCount?:number};
const empty={title:'',description:'',audioUrl:'',thumbnailUrl:'',accessType:'FREE'};

export default function AudioManager(){
 const {idToken}=useAuth(); const [items,setItems]=useState<Item[]>([]); const [type,setType]=useState('tracks'); const [show,setShow]=useState(false); const [editing,setEditing]=useState<Item|null>(null); const [form,setForm]=useState<any>(empty); const [status,setStatus]=useState(''); const [busy,setBusy]=useState('');
 const load=async()=>{if(!idToken)return;setStatus('');const r=await fetch(`/api/admin/content?type=${type}&limit=100`,{headers:{Authorization:`Bearer ${idToken}`},cache:'no-store'});const j=await r.json();if(r.ok)setItems(j.data.items||[]);else setStatus(j.error||'Unable to load sources')};
 useEffect(()=>{load()},[idToken,type]);
 const openNew=()=>{setEditing(null);setForm(empty);setShow(true);setStatus('')};
 const openEdit=(x:Item)=>{setEditing(x);setForm({title:x.title,description:x.description||'',audioUrl:x.audioUrl,thumbnailUrl:x.thumbnailUrl||'',accessType:x.accessType||'FREE'});setShow(true);setStatus('')};
 const save=async(e:any)=>{e.preventDefault();if(!idToken)return;setStatus('Saving…');const payload={type,title:String(form.title).trim(),description:String(form.description||''),audioUrl:String(form.audioUrl).trim(),thumbnailUrl:String(form.thumbnailUrl||'').trim()||undefined,accessType:form.accessType,status:'PUBLISHED'};const r=await fetch('/api/admin/content',{method:editing?'PATCH':'POST',headers:{Authorization:`Bearer ${idToken}`,'Content-Type':'application/json'},body:JSON.stringify(editing?{...payload,id:editing.id}:payload)});const j=await r.json();if(!r.ok){setStatus(j.error||'Save failed');return}setShow(false);setEditing(null);setStatus('Saved');await load()};
 const action=async(x:Item,kind:'block'|'unblock'|'delete')=>{if(!idToken)return;if(kind==='delete'&&!confirm(`Permanently delete “${x.title}”?`))return;setBusy(x.id+kind);try{let r:Response;if(kind==='delete')r=await fetch(`/api/admin/content?type=${type}&id=${encodeURIComponent(x.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${idToken}`}});else r=await fetch('/api/admin/content',{method:'PATCH',headers:{Authorization:`Bearer ${idToken}`,'Content-Type':'application/json'},body:JSON.stringify({type,id:x.id,status:kind==='block'?'BLOCKED':'PUBLISHED'})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Action failed');await load()}catch(e:any){setStatus(e.message||'Action failed')}finally{setBusy('')}};
 return <main className="space-y-6"><header className="skeuo-panel flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">AUDIO CMS</p><h1 className="mt-2 text-3xl font-black">Audio Sources</h1><p className="mt-1 text-sm text-dark-muted">Live licensed HTTPS sources. Edit, block, restore or permanently delete every record.</p></div><div className="flex gap-2"><button onClick={load} className="skeuo-button inline-flex items-center gap-2"><RefreshCw size={16}/> Refresh</button><button onClick={openNew} className="skeuo-button-primary inline-flex items-center gap-2"><Plus size={17}/> Add source</button></div></header>
 <div className="flex gap-2"><select value={type} onChange={e=>setType(e.target.value)} className="input max-w-xs"><option value="tracks">Tracks</option><option value="podcasts">Podcasts</option><option value="episodes">Episodes</option></select></div>
 {status&&<div className="skeuo-card p-4 text-sm text-dark-muted">{status}</div>}
 {show&&<form onSubmit={save} className="skeuo-card grid gap-4 p-6 md:grid-cols-2"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required maxLength={200} placeholder="Title" className="input"/><input value={form.thumbnailUrl} onChange={e=>setForm({...form,thumbnailUrl:e.target.value})} type="url" placeholder="Cover image URL (optional)" className="input"/><input value={form.audioUrl} onChange={e=>setForm({...form,audioUrl:e.target.value})} required type="url" placeholder="HTTPS audio URL" className="input md:col-span-2"/><select value={form.accessType} onChange={e=>setForm({...form,accessType:e.target.value})} className="input"><option>FREE</option><option>PREMIUM</option></select><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={5000} placeholder="Description" className="input md:col-span-2 min-h-24"/><div className="flex gap-2 md:col-span-2"><button className="skeuo-button-primary inline-flex items-center gap-2"><Check size={15}/>{editing?'Update source':'Publish source'}</button><button type="button" onClick={()=>setShow(false)} className="skeuo-button inline-flex items-center gap-2"><X size={15}/> Cancel</button></div></form>}
 <div className="grid gap-4 md:grid-cols-2">{items.map(x=><article key={x.id} className={`skeuo-card p-5 ${x.status==='BLOCKED'?'opacity-60':''}`}><div className="flex items-start gap-3"><FileAudio className="mt-1 text-accent"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-black">{x.title}</h2><p className="mt-1 text-xs text-dark-muted">{x.accessType||'FREE'} · {x.status||'DRAFT'} · {Number(x.playCount||0).toLocaleString()} plays</p></div><div className="flex shrink-0 gap-1"><button onClick={()=>openEdit(x)} className="skeuo-button p-2" title="Edit"><Pencil size={14}/></button><button disabled={!!busy} onClick={()=>action(x,x.status==='BLOCKED'?'unblock':'block')} className="skeuo-button p-2 disabled:opacity-50" title={x.status==='BLOCKED'?'Restore':'Block'}><Ban size={14}/></button><button disabled={!!busy} onClick={()=>action(x,'delete')} className="skeuo-button p-2 text-red-300 disabled:opacity-50" title="Delete"><Trash2 size={14}/></button></div></div><a className="mt-3 flex items-center gap-1 truncate text-xs text-accent" href={x.audioUrl} target="_blank" rel="noreferrer"><ExternalLink size={13}/>{x.audioUrl}</a></div></div></article>)}{!items.length&&<div className="skeuo-card p-10 text-center text-sm text-dark-muted md:col-span-2">No records yet. Add your first licensed audio source.</div>}</div></main>
}
