"use client";
import { useEffect,useState } from 'react';
import { Heart,Loader2,RefreshCw } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { usePlayer } from '@/components/player/PlayerProvider';
import { Track } from '@/types';
import TrackCard from '@/components/tracks/TrackCard';

export default function FavoritesPage(){const{ idToken }=useAuth();const{play}=usePlayer();const[favorites,setFavorites]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=async()=>{if(!idToken){setLoading(false);return}setLoading(true);try{const r=await fetch('/api/me/favorites',{headers:{Authorization:`Bearer ${idToken}`},cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load favorites');setFavorites(j.data?.items||[])}catch(e:any){setError(e.message||'Unable to load favorites')}finally{setLoading(false)}};useEffect(()=>{load()},[idToken]);const remove=async(id:string)=>{if(!idToken)return;const r=await fetch('/api/me/favorites',{method:'POST',headers:{Authorization:`Bearer ${idToken}`,'Content-Type':'application/json'},body:JSON.stringify({trackId:id})});if(r.ok)setFavorites(v=>v.filter(x=>(x.trackId||x.id)!==id))};const tracks:Track[]=favorites.map(x=>({id:x.trackId||x.id,title:x.title||'Untitled',slug:'',description:x.description||'',thumbnailUrl:x.thumbnailUrl||'',audioUrl:x.audioUrl||'',categoryId:'',creatorId:'',accessType:x.accessType==='PREMIUM'?'PREMIUM':'FREE',status:'PUBLISHED',featured:false,explicitContent:false,language:'',releaseDate:0,duration:Number(x.duration||0),playCount:0,likeCount:0,createdAt:Number(x.createdAt||0),updatedAt:Number(x.createdAt||0)}));return <main className="mx-auto max-w-7xl space-y-8 p-4 pb-32 sm:p-6 md:p-10"><header className="skeuo-panel flex items-center justify-between p-6"><div><p className="eyebrow flex items-center gap-2"><Heart size={14}/> YOUR DATA</p><h1 className="mt-2 text-3xl font-black">Favorites</h1><p className="mt-1 text-sm text-dark-muted">Saved directly to your authenticated Firestore account.</p></div><button onClick={load} className="skeuo-button inline-flex items-center gap-2"><RefreshCw size={15}/> Refresh</button></header>{error&&<div className="skeuo-card p-4 text-sm text-red-300">{error}</div>}{loading?<div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-accent"/></div>:tracks.length?<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{tracks.map(t=><TrackCard key={t.id} track={t} onPlay={x=>void play(x,tracks)} onToggleFavorite={remove} isFavorite={true}/>)}</div>:<div className="skeuo-card p-12 text-center text-sm text-dark-muted">No favorites saved yet.</div>}</main>}
