"use client";
import React, { useEffect, useState } from "react";
import { LogOut, RefreshCw, ShieldCheck, Trophy, User, WalletCards } from "lucide-react";
import Link from "next/link";
import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import { auth } from "@/lib/firebase";

type Profile={displayName?:string;email?:string;coinBalance:number;totalWins:number;totalTournaments:number;role:string};
export default function AccountPage(){const{user,loading,idToken}=useAuth();const router=useRouter();const[profile,setProfile]=useState<Profile|null>(null);const[busy,setBusy]=useState(false);const load=async()=>{if(!idToken)return;setBusy(true);try{const r=await fetch('/api/profile',{headers:{Authorization:`Bearer ${idToken}`},cache:'no-store'});const j=await r.json();if(r.ok)setProfile(j.data)}finally{setBusy(false)}};useEffect(()=>{if(!loading&&!user)router.push('/login')},[user,loading,router]);useEffect(()=>{void load()},[idToken]);const signOut=async()=>{await auth.signOut();router.push('/')};if(loading||!user)return <div className="p-12 text-center text-white">Loading account...</div>;return <div className="mx-auto max-w-5xl space-y-7 p-5 pb-32 md:p-10"><header className="rounded-3xl border border-accent/20 bg-accent/5 p-6 md:p-8"><p className="text-xs font-black uppercase tracking-widest text-accent">PLAYER PROFILE</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-black"><User className="text-accent"/> {profile?.displayName||user.displayName||'Player'}</h1><p className="mt-2 text-sm text-dark-muted">{profile?.email||user.email}</p><button onClick={()=>void load()} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-dark-border px-4 py-2 text-sm font-bold"><RefreshCw size={15} className={busy?'animate-spin':''}/> Refresh</button></header><section className="grid gap-4 sm:grid-cols-3"><Stat icon={WalletCards} label="Coin balance" value={`${profile?.coinBalance??0}`} /><Stat icon={Trophy} label="Tournament wins" value={`${profile?.totalWins??0}`} /><Stat icon={Trophy} label="Events played" value={`${profile?.totalTournaments??0}`} /></section><section className="rounded-2xl border border-dark-border bg-dark-card p-6"><div className="flex items-center gap-2 font-black"><ShieldCheck className="text-accent" size={18}/> Account security</div><p className="mt-2 text-sm text-dark-muted">Authentication is handled by Firebase. Platform roles and coin balances are protected server-side.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/wallet" className="rounded-xl bg-accent px-4 py-2.5 font-black text-dark">Open wallet</Link><Link href="/tournaments" className="rounded-xl border border-dark-border px-4 py-2.5 font-bold">Browse tournaments</Link><button onClick={signOut} className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-2.5 font-bold text-red-300">Sign out</button></div></section></div>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <article className="rounded-2xl border border-dark-border bg-dark-card p-5"><Icon className="text-accent" size={21}/><p className="mt-3 text-sm text-dark-muted">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>}
